spring:
  application:
    name: server
  data:
    redis:
      host: localhost
      username: default
      password: systempass

server:
  port: 19090

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:19090/eureka/
  instance:
    hostname: localhost


