spring:
  application:
    name: server

server:
  port: 1909

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:19090/eureka/
  instance:
    hostname: localhost


